### ISSUE TITLE
Unable to translate

### ISSUE THREAD

**Issue by sk8darr** [benoitfragit/google2ubuntu#63]
Hey, im stil having a issue!

I already have a api key and all dependencies. 
I was trying with all the solutions given to problems already registered, but keeps saying that it can not translate.

[SPANISH,DEV]

/usr/share/google2ubuntu$ ./google2ubuntu.py 

/usr/share/google2ubuntu/resources/sound.wav:

 File Size: 55.0k     Bit Rate: 708k
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 22050Hz      
Replaygain: off         
  Duration: 00:00:00.62  

In:100%  00:00:00.62 [00:00:00.00] Out:13.7k [ -====|====- ]        Clip:0    
Done.
config file: /home/sk8/.config/google2ubuntu/google2ubuntu.xml

Some help please.

**Comment by lincus** [comment]
The developer discontinued google2ubuntu. Google for Pocketvox, it is a replacement program by the same developer.

**Comment by sk8darr** [comment]
O, thnks. Let's try!
